name: Encrypty Workflow
run-name: ${{ github.actor }} is running a workflow.
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build
        run: |
          make build
          ls
  
  test:
    runs-on: ubuntu-latest
    steps:
       - if: false
       - name: Check out repository code
         uses: actions/checkout@v4
       - name: Test
         run: |
           make build
           timeout 1m make test
