name: Encrypty Workflow
run-name: ${{ github.actor }} is running a workflow.
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build
        run: |
          make build
          ls
  
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
       - name: Check out repository code
         uses: actions/checkout@v4
       - name: Build
         run: |
           make build
           make test
